name: update-7dtd-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-7dtd-build:
    uses: Gluck-House/7dtd-mod-infra/.github/workflows/reusable-update-7dtd-build.yml@main
    secrets: inherit
